Repository cosmo-workspace/cosmo, pull requests merged in 2022-10, with the labels that each got.

#562 [controller-manager]Support port number change
  charts/cosmo-controller-manager/templates/manager.yaml
  cmd/controller-manager/main.go
Labels: improvement, controller-manager

#587 Bump year
  LICENSE
  api/core/v1alpha1/zz_generated.deepcopy.go
  api/workspace/v1alpha1/zz_generated.deepcopy.go
  cmd/auth-proxy/main.go
  cmd/controller-manager/main.go
  cmd/dashboard/main.go
  hack/boilerplate.go.txt
  internal/cmd/root_cmd.go
Labels: chore

#586 Update cosmoctl commands
  internal/cmd/__snapshots__/netrule_test.snap
  internal/cmd/__snapshots__/workspace_test.snap
  internal/cmd/create/cmd.go
  internal/cmd/delete/cmd.go
  internal/cmd/get/cmd.go
  internal/cmd/netrule/cmd.go
  internal/cmd/netrule/create.go
  internal/cmd/netrule/delete.go
  internal/cmd/netrule_test.go
  internal/cmd/root_cmd.go
  internal/cmd/run/cmd.go
  internal/cmd/stop/cmd.go
  internal/cmd/template/cmd.go
  internal/cmd/template/generate.go
  internal/cmd/template/get.go
  internal/cmd/template/validate.go
  internal/cmd/user/cmd.go
  internal/cmd/user/create.go
  internal/cmd/user/delete.go
  internal/cmd/user/get.go
  internal/cmd/user/reset_password.go
  internal/cmd/user/update.go
  internal/cmd/workspace/cmd.go
  internal/cmd/workspace/create.go
  internal/cmd/workspace/delete.go
  internal/cmd/workspace/get.go
  internal/cmd/workspace/run_instance.go
  internal/cmd/workspace/stop_instance.go
  internal/cmd/workspace_test.go
Labels: improvement, cosmoctl, go, refactoring

#592 [auth-proxy] Change protocol to proto3
  go.mod
  go.sum
  internal/authproxy/proxy/handler.go
  internal/authproxy/proxy/server.go
  pkg/auth/authorizer.go
  pkg/auth/http_authorizer.go
  pkg/auth/password_authorizer.go
  proto/Makefile
  proto/def/auth-proxy/v1alpha1/authproxy.proto
  proto/def/buf.gen.yaml
  proto/def/buf.work.yaml
  proto/def/buf.yaml
  proto/gen/auth-proxy/v1alpha1/authproxy.pb.go
  proto/gen/auth-proxy/v1alpha1/authproxyconnect/authproxy.connect.go
  web/auth-proxy-ui/README.md
  web/auth-proxy-ui/package.json
  web/auth-proxy-ui/src/auth-proxy/v1alpha1/authproxy_connectweb.ts
  web/auth-proxy-ui/src/auth-proxy/v1alpha1/authproxy_pb.ts
  web/auth-proxy-ui/src/views/pages/SignIn.tsx
  web/auth-proxy-ui/yarn.lock
Labels: auth-proxy, dependencies, refactoring

#600 Fix authorizer package to use AuthRequest interface
  api/openapi/dashboard/v1alpha1/auth_request_impl.go
  hack/api-generate/Makefile
  hack/api-generate/go-server/auth_request_impl.go_
  hack/proxy-driver/main.go
  internal/dashboard/auth_handler.go
  pkg/auth/authorizer.go
  pkg/auth/dashboard_authorizer.go
  pkg/auth/password_secret_authorizer.go
Labels: bug
