Repository cosmo-workspace/cosmo, pull requests merged in 2022-07, with the labels that each got.

#401 Fix bugs
  internal/controllers/cluster_instance_controller_test.go
  internal/controllers/cluster_template_controller_test.go
  internal/controllers/instance_controller.go
  internal/controllers/instance_controller_test.go
  internal/controllers/template_controller_test.go
  internal/controllers/user_controller_test.go
  internal/controllers/workspace_controller_test.go
  internal/webhooks/instance_webhook.go
  internal/webhooks/instance_webhook_test.go
  internal/webhooks/template_webhook.go
  internal/webhooks/user_webhook.go
  internal/webhooks/workspace_webhook.go
Labels: bug, controller-manager

#402 Fix bugs with #382
  hack/local-run-test/Makefile
  internal/controllers/instance_controller.go
  internal/dashboard/__snapshots__/user_handler_test.snap
  pkg/kosmo/password.go
Labels: bug, auth-proxy

#405 Fixed: the version# of cosmo modules in the container is not updated when release action
  .github/workflows/release.yaml
Labels: chore

#430 [auth-proxy] Fix bugs in auth-proxy reconcile
  api/workspace/v1alpha1/workspace_types.go
  internal/authproxy/__snapshots__/reconciler_test.snap
  internal/authproxy/proxy/manager.go
  internal/authproxy/public/index.html
  internal/authproxy/reconciler.go
  internal/authproxy/reconciler_test.go
  internal/authproxy/suite_test.go
  pkg/kosmo/test/test_util.go
Labels: bug, auth-proxy

#436 Fix:normal user must not be able to delete users
  internal/dashboard/user_handler.go
  internal/dashboard/user_handler_test.go
Labels: bug, dashboard

#432 Chore:Update envtest to v1.21.x, test code refactoring ,etc.
  Makefile
  hack/local-run-test/Makefile
  internal/cmd/__snapshots__/template_test.snap
  internal/cmd/__snapshots__/user_test.snap
  internal/cmd/__snapshots__/workspace_test.snap
  internal/cmd/workspace_test.go
Labels: chore, refactoring

#437 PortName should be limited less than 15 characters
  internal/webhooks/__snapshots__/workspace_webhook_test.snap
  internal/webhooks/workspace_webhook.go
  internal/webhooks/workspace_webhook_test.go
Labels: improvement, controller-manager

#438 [dashboard]Prevent deletion of own user
  internal/dashboard/__snapshots__/user_handler_test.snap
  internal/dashboard/user_handler.go
  internal/dashboard/user_handler_test.go
Labels: improvement, dashboard

#439 [cosmoctl] Modify addon flag
  internal/cmd/__snapshots__/user_test.snap
  internal/cmd/user/create.go
  internal/cmd/user_test.go
Labels: improvement, cosmoctl, breaking-change

#440 Port name rename
  internal/cmd/__snapshots__/workspace_test.snap
  internal/cmd/workspace/add_net_rule.go
  internal/cmd/workspace/cmd.go
  internal/cmd/workspace/remove_net_rule.go
  internal/cmd/workspace_test.go
Labels: improvement, cosmoctl, breaking-change
